name: DevOps Dashboard CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t devops-dashboard .
      - name: Run test
        run: echo "Tests passed!"
